name: Github-Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/viacomcbs/dsnp-common-go-lib
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Configure git
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: pip install mkdocs-material
      - run: pip install mkdocs-multirepo-plugin
      - run: mkdocs gh-deploy --force --clean --verbose
